// ── ULTRON v9 — multi-format rules generation ─────────────────────────────────

import * as memoryRepo from "../repositories/memory.repo.js";
import type { Category } from "../db/types.js";

type RulesFormat = "claude" | "cursor" | "agents";

export function generateRules(project: string, format: RulesFormat, categories?: Category[]): string {
  const cats: Category[] = categories?.length
    ? categories
    : ["rule", "warning", "pattern", "preference"];
  const memories = memoryRepo.getRulesMemories(project, cats);
  if (memories.length === 0) return `No memories in [${cats.join(", ")}] for '${project}'.`;

  const grouped: Record<string, typeof memories> = {};
  for (const m of memories) (grouped[m.category] ??= []).push(m);

  if (format === "cursor") return formatCursorRules(project, grouped);
  if (format === "agents") return formatAgentsMd(project, grouped);
  return formatClaudeMd(project, grouped);
}

function formatClaudeMd(project: string, grouped: Record<string, Array<{ key: string; value: string; category: string }>>): string {
  let md = `# Project Rules: ${project}\n# Generated by ULTRON Hub v9\n\n`;
  const section = (cat: string, title: string, comment: string, withKey = false) => {
    if (!grouped[cat]) return;
    md += `## ${title}\n<!-- ${comment} -->\n\n`;
    for (const m of grouped[cat]) md += withKey ? `- **${m.key}**: ${m.value}\n` : `- ${m.value}\n`;
    md += "\n";
  };
  section("rule", "Non-negotiable Rules", "Always active — injected first");
  section("warning", "Avoid", "Learned from real experience");
  section("pattern", "Follow", "Patterns that work in this project");
  section("preference", "Preferences", "Team conventions");
  section("fact", "Facts", "Key project data", true);
  md += `---\n_Generated by ULTRON Hub v9 on ${new Date().toISOString().split("T")[0]}_\n`;
  return md;
}

function formatCursorRules(
  project: string,
  grouped: Record<string, Array<{ key: string; value: string; category: string }>>
): string {
  let out = `---\ndescription: Project rules for ${project} (generated by ULTRON)\nglobs: **/*\nalwaysApply: true\n---\n\n`;
  out += `# ${project} — ULTRON Rules\n\n`;
  for (const [cat, items] of Object.entries(grouped)) {
    out += `## ${cat}\n\n`;
    for (const m of items) out += `- ${cat === "fact" ? `**${m.key}**: ` : ""}${m.value}\n`;
    out += "\n";
  }
  return out;
}

function formatAgentsMd(
  project: string,
  grouped: Record<string, Array<{ key: string; value: string; category: string }>>
): string {
  let md = `# AGENTS.md — ${project}\n\n> Generated by ULTRON Hub v9. Paste into project root for any AI agent.\n\n`;
  md += `## Session protocol\n\n1. Call \`session_start("${project}", "<tool>", slim=true)\`\n`;
  md += `2. Save knowledge with \`remember\`, \`decision\`, \`task\`\n`;
  md += `3. Close with \`session_end("${project}", "<tool>", summary, files)\`\n\n`;
  for (const [cat, items] of Object.entries(grouped)) {
    md += `## ${cat.charAt(0).toUpperCase() + cat.slice(1)}\n\n`;
    for (const m of items) md += `- ${m.value}\n`;
    md += "\n";
  }
  return md;
}
